# Generated by Django 4.2.2 on 2023-06-27 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_Circuito', models.CharField(max_length=45, null=True)),
                ('nombre_Circuito', models.CharField(max_length=45, null=True)),
                ('no_Subcircuitos', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Circuitos',
                'db_table': 'Circuito',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, choices=[('Loja', 'Loja'), ('otr', 'otra..')], db_column='Provincia', max_length=26, null=True)),
                ('no_circuitos', models.CharField(max_length=45, null=True)),
                ('parroquia', models.CharField(blank=True, choices=[('VILCABAMBA', 'VILCABAMBA(VICTORIA)'), ('QUINARA', '(QUINARA)'), ('MALACATOS', 'MALACATOS(VALLADOLID)'), ('CHUQUIRIBAMBA', '(CHUQUIRIBAMBA)'), ('TAQUIL', 'TAQUIL(MIGUEL RIOFRIO)'), ('Loja', 'LOJA(LOJA)')], db_column='Parroqia', max_length=26, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dependencias',
                'db_table': 'Dependencia',
            },
        ),
        migrations.CreateModel(
            name='FlotaVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('Auto', 'Automóvil'), ('Moto', 'Motocicleta'), ('Camioneta', 'Camioneta')], db_column='Tipo de Vehículo', max_length=26, null=True)),
                ('placa', models.CharField(max_length=45, null=True)),
                ('chasis', models.CharField(max_length=45, null=True)),
                ('marca', models.CharField(max_length=45, null=True)),
                ('modelo', models.CharField(max_length=45, null=True)),
                ('motor', models.CharField(db_column='Motor Marca', max_length=45, null=True)),
                ('kilometraje', models.IntegerField(null=True)),
                ('cilindraje', models.CharField(max_length=45, null=True)),
                ('capacidad_de_carga', models.CharField(max_length=45, null=True)),
                ('capacidad_de_pasajeros', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Flota vehicular',
                'db_table': 'Flota Vehicular',
            },
        ),
        migrations.CreateModel(
            name='OrdendeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('estado', models.CharField(blank=True, choices=[('Activa', 'Orden activa'), ('Despachada', 'Orden despachada')], db_column='Estado de Orden', max_length=26, null=True)),
                ('tipo_orden', models.CharField(blank=True, choices=[('Mantenimiento', 'Orden de Mantenimiento'), ('Combsustible', 'Orden de combustible')], db_column='Tipo de orden', max_length=26, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de trabajo',
                'db_table': 'Ordenes de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='TallerMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico_responsable', models.CharField(max_length=45, null=True)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('direccion', models.TextField(max_length=45, null=True)),
                ('telefono', models.CharField(max_length=45, null=True)),
                ('tipo_taller', models.CharField(blank=True, choices=[('Institucional', 'Taller institucional'), ('Particular', 'Taller particular')], db_column='Tipo de taller', max_length=26, null=True)),
            ],
            options={
                'verbose_name_plural': 'Telleres Mecánicos',
                'db_table': 'Taller mecanico',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='Genero', max_length=1, null=True)),
                ('identificacion', models.CharField(db_column='Identificacion', max_length=50, null=True)),
                ('rango', models.CharField(blank=True, choices=[('Pol', 'Policía'), ('CS', 'Cabo Segundo'), ('CP', 'Cabo Primero'), ('SaS', 'Sargento Segundo'), ('SaP', 'Sargento Primero'), ('SoS', 'Suboficial Segundo'), ('SoP', 'Suboficial Primero'), ('ST', 'Subteniente'), ('Te', 'Teniente'), ('CaP', 'Capitán'), ('MaY', 'Mayor'), ('TeC', 'Teniente Coronel')], db_column='Rango', max_length=3, null=True)),
                ('tipo_sange', models.CharField(blank=True, choices=[('A+', 'A positivo'), ('A-', 'A negativo'), ('B+', 'B positivo'), ('B-', 'B negativo'), ('AB+', 'AB positivo'), ('AB-', 'AB negativo'), ('O+', 'O positivo'), ('O-', 'O negativo')], db_column='Tipo de sangre', max_length=3, null=True)),
                ('user', models.OneToOneField(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Datos de usuario',
                'db_table': 'Usuario datos',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.usuario')),
            ],
            options={
                'verbose_name_plural': 'Encargados de logística',
                'db_table': 'Tecnico',
            },
        ),
        migrations.CreateModel(
            name='Subcircuitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_subcircuito', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_subcircuito', models.CharField(blank=True, max_length=45, null=True)),
                ('subcircuitoCircuito', models.ForeignKey(db_column='Circuito_idCircuito', on_delete=django.db.models.deletion.DO_NOTHING, to='home.circuito')),
            ],
            options={
                'verbose_name_plural': 'Subcircuitos',
                'db_table': 'Subcircuitos',
            },
        ),
        migrations.CreateModel(
            name='PersonalPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcircuito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.subcircuitos')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_UsuarioID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.usuario')),
            ],
            options={
                'verbose_name_plural': 'Personal Policial',
                'db_table': 'Personal Policial',
            },
        ),
        migrations.CreateModel(
            name='PartePolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, max_length=45, null=True)),
                ('tipo_parte', models.CharField(blank=True, choices=[('Tipo 01', 'Mantenimiento preventivo'), ('Tipo 02', 'Mantenimiento emergente'), ('Tipo 03', 'Novedades')], db_column='Tipo de combustible', max_length=26, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=45, null=True)),
                ('personalPolicial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.personalpolicial')),
            ],
            options={
                'verbose_name_plural': 'Partes Policiales',
                'db_table': 'Parte Policial',
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(blank=True, choices=[('M1', 'Mantenimiento tipo 01'), ('M2', 'Mantenimiento tipo 02'), ('M3', 'Mantenimiento tipo 03')], db_column='Tipo de Mantenimiento', max_length=26, null=True)),
                ('ordende_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ordendetrabajo')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Mantenimiento',
                'db_table': 'Ordenes de Mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.tecnico'),
        ),
        migrations.CreateModel(
            name='OrdenCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_combustible', models.CharField(blank=True, choices=[('Diesel', 'Combustible Diesel'), ('Extra', 'Combustible Extra'), ('Super', 'Combustible Super')], db_column='Tipo de combustible', max_length=26, null=True)),
                ('cantidad_galones', models.CharField(max_length=45, null=True)),
                ('cantidad_galones_detalle', models.CharField(max_length=45, null=True)),
                ('ordende_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ordendetrabajo')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Combustible',
                'db_table': 'Ordenes de Combustible',
            },
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ordenmantenimiento')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.tallermecanico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.flotavehicular')),
            ],
            options={
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'Mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='flotavehicular',
            name='subcircuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.subcircuitos'),
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_Distrito', models.CharField(max_length=45, null=True)),
                ('nombre_Distrito', models.CharField(max_length=45, null=True)),
                ('no_Circuitos', models.IntegerField(null=True)),
                ('distritoDependencia', models.ForeignKey(db_column='idDependencia', on_delete=django.db.models.deletion.DO_NOTHING, to='home.dependencia')),
            ],
            options={
                'verbose_name_plural': 'Distritos',
                'db_table': 'Distrito',
            },
        ),
        migrations.AddField(
            model_name='circuito',
            name='circuitoDistrito',
            field=models.ForeignKey(db_column='Distrito_id', on_delete=django.db.models.deletion.DO_NOTHING, to='home.distrito'),
        ),
    ]
