# Generated by Django 4.2.2 on 2023-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tallermecanico',
            options={'verbose_name_plural': 'Talleres Mecánicos'},
        ),
        migrations.AlterField(
            model_name='partepolicial',
            name='observaciones',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
