# Generated by Django 4.2.2 on 2023-07-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parroquia',
            options={'verbose_name_plural': 'Parroquias'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelTable(
            name='parroquia',
            table='Parroquia',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='Provincia',
        ),
    ]
