# Generated by Django 4.2.2 on 2023-07-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_sange',
            new_name='tipo_sangre',
        ),
    ]
