# Generated by Django 4.2.2 on 2023-07-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_rango_ctlg_options_alter_rango_ctlg_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='circuitoDistrito',
            field=models.ForeignKey(db_column='Distrito_id', on_delete=django.db.models.deletion.CASCADE, related_name='circuito', to='home.distrito'),
        ),
    ]
