# Generated by Django 4.2.2 on 2023-07-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_circuito_circuitodistrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcircuitos',
            name='subcircuitoCircuito',
            field=models.ForeignKey(db_column='Circuito_idCircuito', on_delete=django.db.models.deletion.CASCADE, related_name='subcircuito', to='home.circuito'),
        ),
        migrations.CreateModel(
            name='QuejaSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=10)),
                ('detalles', models.TextField()),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.circuito')),
                ('subcircuito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.subcircuitos')),
            ],
        ),
    ]
