# Generated by Django 4.2.2 on 2023-07-03 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_partepolicial_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(db_column='Identificacion', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La identificación debe ser exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
