# Generated by Django 4.2.2 on 2023-07-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_usuario_direccion_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalpolicial',
            name='usuario',
            field=models.OneToOneField(blank=True, db_column='usuario_UsuarioID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home.usuario'),
        ),
    ]
