# Generated by Django 4.2.2 on 2023-07-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_subcircuitos_subcircuitocircuito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tipo_orden',
            field=models.CharField(blank=True, choices=[('Mantenimiento', 'Orden de Mantenimiento'), ('Combustible', 'Orden de combustible')], db_column='Tipo de orden', max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
    ]
