# Generated by Django 4.2.2 on 2023-07-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_personalpolicial_usuario_alter_tecnico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalpolicial',
            name='subcircuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PersonalPolicial_Subcircuito', to='home.subcircuitos'),
        ),
    ]
