# Generated by Django 4.2.2 on 2023-07-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_ordendetrabajo_tipo_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpolicial',
            name='flota_vehicular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_policial5', to='home.flotavehicular'),
        ),
        migrations.AddField(
            model_name='personalpolicial',
            name='turno_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalpolicial',
            name='turno_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
