# Generated by Django 4.2.2 on 2023-07-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_personalpolicial_flota_vehicular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalpolicial',
            name='subcircuito',
        ),
        migrations.AlterField(
            model_name='flotavehicular',
            name='subcircuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flota_vehicular', to='home.subcircuitos'),
        ),
        migrations.AlterField(
            model_name='personalpolicial',
            name='flota_vehicular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_policial', to='home.flotavehicular'),
        ),
    ]
