# Generated by Django 4.2.2 on 2023-07-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_personalpolicial_subcircuito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, max_length=810, null=True),
        ),
    ]
