# Generated by Django 4.2.2 on 2023-07-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='titular',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
