# Generated by Django 4.2.2 on 2023-07-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_ordencombustible_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partepolicial',
            name='orden_combustible',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ordencombustible'),
        ),
        migrations.AddField(
            model_name='partepolicial',
            name='orden_mantenimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ordenmantenimiento'),
        ),
    ]
