# Generated by Django 4.2.2 on 2023-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_partepolicial_orden_combustible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partepolicial',
            name='tipo_parte',
            field=models.CharField(blank=True, choices=[('Mantenimiento Preventivo', 'Mantenimiento preventivo'), ('Mantenimiento Correctivo', 'Mantenimiento correctivo'), ('Solicitud de Combustible', 'Solicitud de combustible'), ('Novedades', 'Novedades')], db_column='Tipo de Parte', max_length=26, null=True),
        ),
    ]
