# Generated by Django 4.2.2 on 2023-07-24 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_partepolicial_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenmantenimiento',
            name='tipo_mantenimiento',
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='tipos_mantenimiento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('M1', 'Mantenimiento tipo 01'), ('M2', 'Mantenimiento tipo 02'), ('M3', 'Mantenimiento tipo 03')], db_column='Tipo de Mantenimiento', max_length=2, null=True), default=list, size=None),
        ),
    ]
