# Generated by Django 4.2.2 on 2023-07-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_ordenmantenimiento_tipo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenmantenimiento',
            old_name='tipos_mantenimiento',
            new_name='tipo_mantenimiento',
        ),
    ]
