# Generated by Django 4.2.2 on 2023-07-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_tipos_mantenimiento_ordenmantenimiento_tipo_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='detalles_mantenimiento',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
