# Generated by Django 4.2.2 on 2023-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_tipomantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencombustible',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
