# Generated by Django 4.2.2 on 2023-08-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_ordencombustible_aprobador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpolicial',
            name='subcircuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_policial', to='home.subcircuitos'),
        ),
    ]
