# Generated by Django 4.2.2 on 2023-09-06 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_flotavehicular_subcircuito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='archivo_asociado',
            field=models.FileField(null=True, upload_to='archivos_asociados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'png'])]),
        ),
    ]
