# Generated by Django 4.2.2 on 2023-09-09 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_ordenmantenimiento_parte_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='parte_asociado',
            field=models.FileField(null=True, upload_to='partes_asociados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'png'])]),
        ),
    ]
