# Generated by Django 4.2.2 on 2023-09-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_ordenmantenimiento_parte_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencombustible',
            name='fecha_de_entrega',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='fecha_de_entrega',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='kilometraje_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
