# Generated by Django 4.2.2 on 2023-09-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_userproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproxy',
            options={'verbose_name_plural': 'UsuariosE info de iusuarios'},
        ),
        migrations.AlterModelTable(
            name='userproxy',
            table='Usuarios_primario',
        ),
    ]
