# Generated by Django 4.2.2 on 2023-09-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_groupproxy_alter_userproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproxy',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelTable(
            name='groupproxy',
            table='Roles_grupos',
        ),
    ]
