# Generated by Django 4.2.2 on 2023-09-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_groupproxy_options_alter_groupproxy_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('datos', models.TextField(max_length=530)),
            ],
        ),
        migrations.AlterModelOptions(
            name='groupproxy',
            options={'verbose_name': 'Rol+', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='userproxy',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Datos de Usuario'},
        ),
        migrations.CreateModel(
            name='OrdenMovilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('ruta', models.CharField(max_length=200)),
                ('kilometraje_inicio', models.IntegerField()),
                ('numero_ocupantes', models.IntegerField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_como_conductor', to='home.personalpolicial')),
                ('ocupantes', models.ManyToManyField(to='home.ocupante')),
                ('personal_policial_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_movilizacion', to='home.personalpolicial')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_movilizacion', to='home.flotavehicular')),
            ],
        ),
    ]
