# Generated by Django 4.2.2 on 2023-09-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_ocupante_alter_groupproxy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocupante',
            options={'verbose_name': 'Ocupante', 'verbose_name_plural': 'Ocupantes'},
        ),
    ]
